///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace Test_Proj_2
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the Test_Proj_2Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.0")]
    [RepositoryFolder("8831f007-02f6-40e1-9ce4-f8d052039847")]
    public partial class Test_Proj_2Repository : RepoGenBaseFolder
    {
        static Test_Proj_2Repository instance = new Test_Proj_2Repository();

        /// <summary>
        /// Gets the singleton class instance representing the Test_Proj_2Repository element repository.
        /// </summary>
        [RepositoryFolder("8831f007-02f6-40e1-9ce4-f8d052039847")]
        public static Test_Proj_2Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public Test_Proj_2Repository() 
            : base("Test_Proj_2Repository", "/", null, 0, false, "8831f007-02f6-40e1-9ce4-f8d052039847", ".\\RepositoryImages\\Test_Proj_2Repository8831f007.rximgres")
        {
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("8831f007-02f6-40e1-9ce4-f8d052039847")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "5.4.0")]
    public partial class Test_Proj_2RepositoryFolders
    {
    }
#pragma warning restore 0436
}